# Generated by Django 4.2 on 2023-05-03 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedetails',
            options={'ordering': ['createdTime']},
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='created',
        ),
        migrations.AddField(
            model_name='recipedetails',
            name='createdTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 19, 54, 9, 191902)),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
