# Generated by Django 4.2 on 2023-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRecipeApp', '0002_alter_recipedetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='category',
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='recipedetails',
            name='category',
            field=models.ManyToManyField(blank=True, to='DjangoRecipeApp.category_tag'),
        ),
    ]
